server:
  port: 8080
  host: 0.0.0.0

declarative:
  ignore-incubating: true

data:
  sources:
    sql:
      - name: "fruitstore"
        provider.hikari:
          username: "fruits"
          password: "fruits"
          url: "jdbc:postgresql://localhost:5432/fruits"
          # jdbc-driver-class-name: "org.postgresql.Driver"
          auto-commit: false
          transaction-isolation: "TRANSACTION_READ_COMMITTED"
          minimum-idle: 10
          maximum-pool-size: 50
          pool-name: "fruitstore"
  persistence-units:
    jakarta:
      - data-source: "fruitstore"
        init-script: "init.sql"
        drop-script: "drop.sql"
        properties:
          # hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
          hibernate.show_sql: false
          hibernate.format_sql: true
          jakarta.persistence.sharedCache.mode: "ENABLE_SELECTIVE"
          hibernate.cache.use_second_level_cache: true
          hibernate.cache.region.factory_class: "jcache"
          hibernate.javax.cache.provider: "com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider"
          hibernate.javax.cache.uri: "caffeine-jcache.conf"
          hibernate.javax.cache.missing_cache_strategy: "fail"
          jakarta.persistence.schema-generation.database.action: "none"
