server:
  port: 8080
  host: 0.0.0.0

fruit-repository:
  type: "caffeine"

db:
  source: jdbc
  connection:
    url: "jdbc:postgresql://localhost:5432/fruits"
    username: "fruits"
    password: "fruits"
    autoCommit: false
    transactionIsolation: "TRANSACTION_READ_COMMITTED"
    minimumIdle: 10
    maximumPoolSize: 50
    poolName: "fruitstore"

cache:
  fruit-repository:
    ttl: "PT30S"
    summary-maximum-size: 1
    entity-maximum-size: 1024
