server:
  port: 8080
  host: 0.0.0.0

db:
  source: jdbc
  connection:
    url: "jdbc:postgresql://localhost:5432/fruits"
    username: "fruits"
    password: "fruits"
    autoCommit: false
    transactionIsolation: "TRANSACTION_READ_COMMITTED"
    minimumIdle: 10
    maximumPoolSize: 50
    poolName: "fruitstore"
