caffeine.jcache {
  default {
    key-type = java.lang.Object
    value-type = java.lang.Object

    store-by-value {
      enabled = false
    }

    monitoring {
      statistics = true
    }
  }

  store {
    policy.maximum.size = 10000
    policy.eager-expiration.after-access = 10m
  }

  storeFruitPriceStore {
    policy.maximum.size = 10000
    policy.eager-expiration.after-access = 10m
  }
}
